export 'package:flutter_componentes/Screens/alert_screen.dart';
export 'package:flutter_componentes/Screens/card_screen.dart';
export 'package:flutter_componentes/Screens/listview1_screen.dart';
export 'package:flutter_componentes/Screens/listview2_screen.dart';
export 'package:flutter_componentes/Screens/home_screen.dart';
export 'package:flutter_componentes/Screens/avatar_screen.dart';
export 'package:flutter_componentes/Screens/animated_screens.dart';
export 'package:flutter_componentes/Screens/inputs_screen.dart';
export 'package:flutter_componentes/Screens/slider_screen.dart';
